# Generated by Django 5.0.1 on 2025-05-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profile_saved_books_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='issue_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='rent_price',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
    ]
